# Generated by Django 5.0.7 on 2024-10-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_webpage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='charanbkumar25@gmail.com', max_length=155),
        ),
    ]
