# Generated by Django 5.0.7 on 2024-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_accessrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
